### PR TITLE
Spine-Error with "Wrong-Type" SNMP-Answer

### PR DESCRIPTION
**Pull request by thomasbuesser**
If you have a SNMP-Device that gives you a "WRONG Type" Answer for a SNMP-Query. Spine removes trailing characters from the answer.

To Reproduce

do SNMP-Query on Host: (Answer should look like that):
IF-MIB::ifHCInOctets.167862272 = Wrong Type (should be Counter64): Hex-STRING: 00 00 00 02 41 CF B4 DC

debug answer in snmp.c from spine ~line 700

debug answer after
snprintf(snmp_oids[i].result, RESULTS_BUFFER, "%s", trim(strip_alpha(temp_result)));

compare values in temp_result <-> snmp_oids[i].result

in snmp_oids[i].result the DC (last two characters) are removed in strip_alpha

Server-OS is FreeBSD 12.1-RELEASE-p1
Cacti / Spine-Release 1.2.7

### CODE REVIEW

**Comment by TheWitness** [comment]
You should base the pull off of the 1.2.x branch instead of develop.  It's easier for the team to merge.

**Comment by thomasbuesser** [comment]
sorry, i'am not familiar with this pull-requests: where can i add the file that needs to be changed?

**Comment by TheWitness** [comment]
Well, the fix looks good, it's just against the wrong branch.  So, save your changes, then delete your fork, then go-to the website, and before you fork, change when branch to 1.2.x.  Then fork and make you changes.  Going to close this one.

**Comment by TheWitness** [comment]
You might have been able to simply change the working branch instead of deleting your fork too.

**Pull request closed without merging**
