### PR TITLE
Fixed reversed strcpy in ping icmp/udp/tcp functions

### LINKED ISSUE #211: 1.2.18 crashes in icmp functions due to reversed strcpy() calls
```
Starting program: /tmp/cacti-spine-1.2.18/spine -C /usr/local/spine/etc/spine.conf --poller 1 --first 0 --last 1091 --mibs
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf]
Version 1.2.18 starting
[Detaching after vfork from child process 139037]
[Detaching after vfork from child process 139038]
[Detaching after vfork from child process 139039]
[Detaching after vfork from child process 139040]
[New Thread 0x7ffff6ea5700 (LWP 139041)]
[New Thread 0x7ffff66a4700 (LWP 139042)]
[New Thread 0x7ffff5ea3700 (LWP 139043)]
[New Thread 0x7ffff56a2700 (LWP 139044)]
[New Thread 0x7ffff4ea1700 (LWP 139045)]
[New Thread 0x7fffe7fff700 (LWP 139046)]
[New Thread 0x7fffe77fe700 (LWP 139047)]
[Thread 0x7ffff6ea5700 (LWP 139041) exited]
2021/07/06 16:43:00 - SPINE: Poller[1] PID[139033] WARNING: Unknown error while resolving host ▒4 (Name or service not known)
free(): invalid pointer
[New Thread 0x7ffff6ea5700 (LWP 139048)]

Thread 3 "spine" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff66a4700 (LWP 139042)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all bt

Thread 9 (Thread 0x7ffff6ea5700 (LWP 139048)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff7c83530 in ?? () at allocatestack.c:311 from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff6ea5700 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7fffe77fe700 (LWP 139047)):
#0  0x00007ffff7ba012b in __GI___select (nfds=80, readfds=0x7fffe77d7870, writefds=0x0, exceptfds=0x0, timeout=0x7fffe77d7830) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007ffff7e5ab91 in snmp_sess_synch_response () from /lib/x86_64-linux-gnu/libnetsnmp.so.35
#2  0x0000555555562a34 in snmp_get (current_host=0x7fffdc0013b0, snmp_oid=0x7fffdc0032f0 ".1.3.6.1.2.1.1.3.0") at snmp.c:367
#3  0x000055555556feec in ping_snmp (host=0x7fffdc0013b0, ping=0x7fffdc002330) at ping.c:193
#4  0x000055555556fc67 in ping_host (host=0x7fffdc0013b0, ping=0x7fffdc002330) at ping.c:94
#5  0x00005555555662d6 in poll_host (host_id=72, host_thread=2, last_host_thread=4, host_data_ids=27, host_time=0x7fffe77fdbd0 "1625604180", host_errors=0x7fffe77fdb00, host_time_double=1625604180.640414) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x5555558608e0) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffe7fff700 (LWP 139046)):
#0  0x00007ffff7ba012b in __GI___select (nfds=79, readfds=0x7fffe7fd8870, writefds=0x0, exceptfds=0x0, timeout=0x7fffe7fd8830) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007ffff7e5ab91 in snmp_sess_synch_response () from /lib/x86_64-linux-gnu/libnetsnmp.so.35
#2  0x0000555555562a34 in snmp_get (current_host=0x7ffff0001aa0, snmp_oid=0x7ffff0003cd0 ".1.3.6.1.2.1.1.3.0") at snmp.c:367
#3  0x000055555556feec in ping_snmp (host=0x7ffff0001aa0, ping=0x7ffff0002a20) at ping.c:193
#4  0x000055555556fc67 in ping_host (host=0x7ffff0001aa0, ping=0x7ffff0002a20) at ping.c:94
#5  0x00005555555662d6 in poll_host (host_id=72, host_thread=1, last_host_thread=4, host_data_ids=27, host_time=0x7fffe7ffebd0 "1625604180", host_errors=0x7fffe7ffeb00, host_time_double=1625604180.640414) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x555555860760) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ffff4ea1700 (LWP 139045)):
#0  __lll_lock_wait (futex=futex@entry=0x555555581360 <seteuid_lock>, private=0) at lowlevellock.c:52
#1  0x00007ffff7c860a3 in __GI___pthread_mutex_lock (mutex=0x555555581360 <seteuid_lock>) at ../nptl/pthread_mutex_lock.c:80
#2  0x000055555556456a in thread_mutex_lock (mutex=2) at locks.c:224
#3  0x00005555555702bd in ping_icmp (host=0x7fffd80013b0, ping=0x7fffd8002330) at ping.c:298
#4  0x000055555556faf3 in ping_host (host=0x7fffd80013b0, ping=0x7fffd8002330) at ping.c:70
#5  0x00005555555662d6 in poll_host (host_id=741, host_thread=4, last_host_thread=4, host_data_ids=44, host_time=0x7ffff4ea0bd0 "1625604180", host_errors=0x7ffff4ea0b00, host_time_double=1625604180.6357591) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x5555558605c0) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffff56a2700 (LWP 139044)):
#0  __lll_lock_wait (futex=futex@entry=0x555555581360 <seteuid_lock>, private=0) at lowlevellock.c:52
#1  0x00007ffff7c860a3 in __GI___pthread_mutex_lock (mutex=0x555555581360 <seteuid_lock>) at ../nptl/pthread_mutex_lock.c:80
#2  0x000055555556456a in thread_mutex_lock (mutex=2) at locks.c:224
#3  0x00005555555702bd in ping_icmp (host=0x7fffe00013b0, ping=0x7fffe0002330) at ping.c:298
#4  0x000055555556faf3 in ping_host (host=0x7fffe00013b0, ping=0x7fffe0002330) at ping.c:70
#5  0x00005555555662d6 in poll_host (host_id=741, host_thread=3, last_host_thread=4, host_data_ids=44, host_time=0x7ffff56a1bd0 "1625604180", host_errors=0x7ffff56a1b00, host_time_double=1625604180.6357591) at poller.c:615
#6  0x0000555555564a52 in child (arg=0x555555860440) at poller.c:103
#7  0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff5ea3700 (LWP 139043)):
#0  futex_wait (private=0, expected=4294967294, futex_word=0x7ffff6ea5d1c) at ../sysdeps/nptl/futex-internal.h:141
#1  futex_wait_simple (private=0, expected=4294967294, futex_word=0x7ffff6ea5d1c) at ../sysdeps/nptl/futex-internal.h:172
#2  setxid_mark_thread (t=t@entry=0x7ffff6ea5700, cmdp=0x7ffff5e7d050) at allocatestack.c:975
#3  0x00007ffff7c82c05 in __nptl_setxid (cmdp=0x7ffff5e7d050) at allocatestack.c:1091
#4  0x00007ffff7b9fc89 in __GI_seteuid (uid=<optimized out>) at ../sysdeps/unix/sysv/linux/seteuid.c:34
#5  __GI_seteuid (uid=<optimized out>) at ../sysdeps/unix/sysv/linux/seteuid.c:24
#6  0x00005555555703fa in ping_icmp (host=0x7fffec0013b0, ping=0x7fffec002330) at ping.c:333
#7  0x000055555556faf3 in ping_host (host=0x7fffec0013b0, ping=0x7fffec002330) at ping.c:70
#8  0x00005555555662d6 in poll_host (host_id=741, host_thread=2, last_host_thread=4, host_data_ids=44, host_time=0x7ffff5ea2bd0 "1625604180", host_errors=0x7ffff5ea2b00, host_time_double=1625604180.6357591) at poller.c:615
#9  0x0000555555564a52 in child (arg=0x555555850d80) at poller.c:103
--Type <RET> for more, q to quit, c to continue without paging--  c
#10 0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff66a4700 (LWP 139042)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7aad859 in __GI_abort () at abort.c:79
#2  0x00007ffff7b183ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c42285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7b2047c in malloc_printerr (str=str@entry=0x7ffff7c404ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff7b21cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007ffff7b91cb0 in __GI_freeaddrinfo (ai=0x0) at ../sysdeps/posix/getaddrinfo.c:2521
#6  0x0000555555572267 in init_sockaddr (name=0x7ffff667e140, hostname=0x7fffe80034b0 "\200\064", port=7) at ping.c:980
#7  0x000055555557062a in ping_icmp (host=0x7fffe80013b0, ping=0x7fffe8002330) at ping.c:377
#8  0x000055555556faf3 in ping_host (host=0x7fffe80013b0, ping=0x7fffe8002330) at ping.c:70
#9  0x00005555555662d6 in poll_host (host_id=741, host_thread=1, last_host_thread=4, host_data_ids=44, host_time=0x7ffff66a3bd0 "1625604180", host_errors=0x7ffff66a3b00, host_time_double=1625604180.6357591) at poller.c:615
#10 0x0000555555564a52 in child (arg=0x555555850d40) at poller.c:103
#11 0x00007ffff7c83609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff7baa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff71c1940 (LWP 139033)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff7c822ec in create_thread (pd=pd@entry=0x7ffff6ea5700, attr=attr@entry=0x7ffffff03a30, stopped_start=stopped_start@entry=0x7ffffff0386e, stackaddr=stackaddr@entry=0x7ffff6ea4dc0, thread_ran=thread_ran@entry=0x7ffffff0386f) at ../sysdeps/unix/sysv/linux/createthread.c:101
#2  0x00007ffff7c83e10 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:817
#3  0x000055555555c7c9 in main (argc=10, argv=0x7fffffffe5d8) at spine.c:824
```

### PR DESCRIPTION
**Pull request by eriksejr**
Fixes #211 and probably #209

### CODE REVIEW

**Comment by majed17** [comment]
after correcting ping.c
```
sudo make
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT ping.o -MD -MP -MF .deps/ping.Tpo -c -o ping.o ping.c
In file included from /usr/include/string.h:519,
                 from common.h:70,
                 from ping.c:34:
In function ‘strncpy’,
    inlined from ‘get_namebyhost’ at ping.c:1027:2:
/usr/include/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |       __glibc_objsize (__dest));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~
ping.c: In function ‘get_namebyhost’:
ping.c:1027:2: note: length computed here
 1027 |  strncpy(stack, hostname, strlen(hostname));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/ping.Tpo .deps/ping.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L/usr/lib64 -L/usr/lib64  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lnetsnmp -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm -lpthread -lssl 
libtool: link: gcc -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lnetsnmp -lmysqlclient -lcrypto -lz -ldl -lm -lpthread -lssl
/usr/bin/help2man --output=spine.1 --name='Data Collector for Cacti' --no-info --version-option='--version' ./spine

```

**Comment by netniV** [comment]
Does that actually correct the issue though?  It seems to put the destination in the source field to me.

**Comment by majed17** [comment]
after make install:
```
sudo -u apache ./spine
SPINE: Using spine config file [/etc/spine.conf]
Version 1.2.18 starting
2021/07/07 10:10:38 - SPINE: Poller[1] PID[400269] ERROR: Spine Timed Out While Processing Available Thread Lock
FATAL: Spine Encountered a Segmentation Fault
Generating backtrace...0 line(s)...

```

**Comment by eriksejr** [comment]
Let me look at it again this morning. Perhaps I was just being to hasty last night and got lucky after compiling and running that.

**Comment by eriksejr** [comment]
@majed17 Unfortunately, this patch was not targeted at your issue - I do not have the issue you do even though I initially thought they were related which is why I moved it out of your thread there. Would have been nice if this fixed it as well, but I did not anticipate it would.

@netniV This seems to be correct. From the manpage for strcpy in Linux:

```SYNOPSIS
       #include <string.h>

       char *strcpy(char *dest, const char *src);

       char *strncpy(char *dest, const char *src, size_t n);
```
In your function you declare then allocate memory for new_hostname on the heap. You then pass new_hostname to init_sockaddr() at line 377 and this is where I was crashing out. The original copy was copying uninitialized memory from new_hostname to host->hostname and overwriting the original hostname.

```
 if (!(new_hostname = (char *) malloc(strlen(host->hostname)+1))) {
                die("ERROR: Fatal malloc error: ping.c ping_icmp() - new_hostname!");
        }

        strcpy(new_hostname, host->hostname);

...

       /* hostname must be nonblank */
        if ((strlen(host->hostname) != 0) && (icmp_socket != -1)) {
                /* initialize variables */
                snprintf(ping->ping_status, 50, "down");
                snprintf(ping->ping_response, SMALL_BUFSIZE, "default");

                /* get address of hostname */
                if (init_sockaddr(&fromname, new_hostname, 7)) {
                        retry_count = 0;
                        total_time  = 0;
                        begin_time  = get_time_as_double();

                        /* initialize file descriptor to review for input/output */
                        FD_ZERO(&socket_fds);
                        FD_SET(icmp_socket,&socket_fds);

```

There are a few other things here I see as well. Are you sure you need new_hostname? init_sockadder() does not seem to change the argument passed in i'm not sure there's a reason to make a copy of it except if perhaps there's an issue with parallelism/locking that I am not aware of, but it's used many other places in the function in its original form. Additionally, the conditional which wraps this block of code references strlen(host->hostname) != 0 rather then new_hostname. If you got rid of it in ping_icmp() then you'd have a patch that looked like this

```root@cacti:/tmp/cacti-spine-1.2.18# diff -u ping.c.orig ping.c
--- ping.c.orig 2021-07-07 08:15:15.686723276 -0400
+++ ping.c      2021-07-07 08:11:00.822746597 -0400
@@ -276,7 +276,6 @@
        struct   ip    *ip;
        struct   icmp  *pkt;
        unsigned char  *packet;
-       char     *new_hostname;

        if (is_debug_device(host->id)) {
                SPINE_LOG(("Device[%i] DEBUG: Entering ICMP Ping", host->id));
@@ -284,12 +283,6 @@
                SPINE_LOG_DEBUG(("Device[%i] DEBUG: Entering ICMP Ping", host->id));
        }

-       if (!(new_hostname = (char *) malloc(strlen(host->hostname)+1))) {
-               die("ERROR: Fatal malloc error: ping.c ping_icmp() - new_hostname!");
-       }
-
-       strcpy(host->hostname, new_hostname);
-
        /* get ICMP socket */
        retry_count = 0;
        while (TRUE) {
@@ -309,7 +302,6 @@
                        if (retry_count > 4) {
                                snprintf(ping->ping_response, SMALL_BUFSIZE, "ICMP: Ping unable to create ICMP Socket");
                                snprintf(ping->ping_status, 50, "down");
-                               free(new_hostname);
                                #if !(defined(__CYGWIN__) && !defined(SOLAR_PRIV))
                                if (hasCaps() != TRUE) {
                                        if (seteuid(getuid()) == -1) {
@@ -374,7 +366,7 @@
                snprintf(ping->ping_response, SMALL_BUFSIZE, "default");

                /* get address of hostname */
-               if (init_sockaddr(&fromname, new_hostname, 7)) {
+               if (init_sockaddr(&fromname, &(host->hostname), 7)) {
                        retry_count = 0;
                        total_time  = 0;
                        begin_time  = get_time_as_double();
@@ -387,16 +379,15 @@
                                if (retry_count > host->ping_retries) {
                                        snprintf(ping->ping_response, SMALL_BUFSIZE, "ICMP: Ping timed out");
                                        snprintf(ping->ping_status, 50, "down");
-                                       free(new_hostname);
                                        free(packet);
                                        close(icmp_socket);
                                        return HOST_DOWN;
                                }

                                if (is_debug_device(host->id)) {
-                                       SPINE_LOG(("Device[%i] DEBUG: Attempting to ping %s, seq %d (Retry %d of %d)", host->id, new_hostname, icmp->icmp_seq, retry_count, host->ping_retries));
+                                       SPINE_LOG(("Device[%i] DEBUG: Attempting to ping %s, seq %d (Retry %d of %d)", host->id, host->hostname, icmp->icmp_seq, retry_count, host->ping_retries));
                                } else {
-                                       SPINE_LOG_DEBUG(("Device[%i] DEBUG: Attempting to ping %s, seq %d (Retry %d of %d)", host->id, new_hostname, icmp->icmp_seq, retry_count, host->ping_retries));
+                                       SPINE_LOG_DEBUG(("Device[%i] DEBUG: Attempting to ping %s, seq %d (Retry %d of %d)", host->id, host->hostname, icmp->icmp_seq, retry_count, host->ping_retries));
                                }

                                /* decrement the timeout value by the total time */
@@ -454,7 +445,6 @@
                                                                }
                                                                snprintf(ping->ping_response, SMALL_BUFSIZE, "ICMP: Device is Alive");
                                                                snprintf(ping->ping_status, 50, "%.5f", total_time);
-                                                               free(new_hostname);
                                                                free(packet);
                                                                #if !(defined(__CYGWIN__) && !defined(SOLAR_PRIV))
                                                                if (hasCaps() != TRUE) {
@@ -506,7 +496,6 @@
                } else {
                        snprintf(ping->ping_response, SMALL_BUFSIZE, "ICMP: Destination hostname invalid");
                        snprintf(ping->ping_status, 50, "down");
-                       free(new_hostname);
                        free(packet);
                        #if !(defined(__CYGWIN__) && !defined(SOLAR_PRIV))
                        if (hasCaps() != TRUE) {
@@ -530,7 +519,6 @@
        } else {
                snprintf(ping->ping_response, SMALL_BUFSIZE, "ICMP: Destination address not specified");
                snprintf(ping->ping_status, 50, "down");
-               free(new_hostname);
                free(packet);
                if (icmp_socket != -1) {
                        #if !(defined(__CYGWIN__) && !defined(SOLAR_PRIV))
```

**Comment by eriksejr** [comment]
In addition, if I'm being pedantic I'd reduce the number of calls in these ping_xxx functions to strlen() by just calling strlen(host->hostname) and sticking that value on the stack then using it where needed. I don't think the value changes anywhere in the function.

**Comment by majed17** [comment]
sudo make
```
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT ping.o -MD -MP -MF .deps/ping.Tpo -c -o ping.o ping.c
ping.c: In function ‘ping_icmp’:
ping.c:369:32: warning: passing argument 2 of ‘init_sockaddr’ from incompatible pointer type [-Wincompatible-pointer-types]
  369 |   if (init_sockaddr(&fromname, &(host->hostname), 7)) {
      |                                ^~~~~~~~~~~~~~~~~
      |                                |
      |                                char (*)[250]
In file included from spine.h:606,
                 from ping.c:35:
ping.h:144:64: note: expected ‘const char *’ but argument is of type ‘char (*)[250]’
  144 | extern int init_sockaddr(struct sockaddr_in *name, const char *hostname, unsigned short int port);
      |                                                    ~~~~~~~~~~~~^~~~~~~~
ping.c: In function ‘ping_udp’:
ping.c:596:34: warning: passing argument 2 of ‘init_sockaddr’ from incompatible pointer type [-Wincompatible-pointer-types]
  596 |   if (init_sockaddr(&servername, &(host->hostname), host->ping_port)) {
      |                                  ^~~~~~~~~~~~~~~~~
      |                                  |
      |                                  char (*)[250]
In file included from spine.h:606,
                 from ping.c:35:
ping.h:144:64: note: expected ‘const char *’ but argument is of type ‘char (*)[250]’
  144 | extern int init_sockaddr(struct sockaddr_in *name, const char *hostname, unsigned short int port);
      |                                                    ~~~~~~~~~~~~^~~~~~~~
ping.c: In function ‘ping_tcp’:
ping.c:759:34: warning: passing argument 2 of ‘init_sockaddr’ from incompatible pointer type [-Wincompatible-pointer-types]
  759 |   if (init_sockaddr(&servername, &(host->hostname), host->ping_port)) {
      |                                  ^~~~~~~~~~~~~~~~~
      |                                  |
      |                                  char (*)[250]
In file included from spine.h:606,
                 from ping.c:35:
ping.h:144:64: note: expected ‘const char *’ but argument is of type ‘char (*)[250]’
  144 | extern int init_sockaddr(struct sockaddr_in *name, const char *hostname, unsigned short int port);
      |                                                    ~~~~~~~~~~~~^~~~~~~~
In file included from /usr/include/string.h:519,
                 from common.h:70,
                 from ping.c:34:
In function ‘strncpy’,
    inlined from ‘get_namebyhost’ at ping.c:990:2:
/usr/include/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |       __glibc_objsize (__dest));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~
ping.c: In function ‘get_namebyhost’:
ping.c:990:2: note: length computed here
  990 |  strncpy(stack, hostname, strlen(hostname));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/ping.Tpo .deps/ping.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L/usr/lib64 -L/usr/lib64  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lnetsnmp -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm -lpthread -lssl 
libtool: link: gcc -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lnetsnmp -lmysqlclient -lcrypto -lz -ldl -lm -lpthread -lssl
/usr/bin/help2man --output=spine.1 --name='Data Collector for Cacti' --no-info --version-option='--version' ./spine

```
i thought i missed some lines, so i just went to the file and selected all the text and pasted it in...could not figure how to download the file instead..
anyway, inspite all this code change:

sudo -u apache ./spine
```
SPINE: Using spine config file [/etc/spine.conf]
Version 1.2.18 starting
2021/07/07 20:27:23 - SPINE: Poller[1] PID[1779772] ERROR: Spine Timed Out While Processing Available Thread Lock
FATAL: Spine Encountered a Segmentation Fault
Generating backtrace...0 line(s)...

```

**Comment by eriksejr** [comment]
@majed17 try to build my forked branch at https://github.com/eriksejr/spine/archive/refs/heads/1.2.x-noNewHostname.zip which has both all these patches. This runs on my cacti install (Ubuntu 20.04) and completes.

If it still segfaults for you then you'll have to provide another full backtrace under GDB. But not sure how much more I can help on this one, i'm not really a C expert.

**Comment by majed17** [comment]
i saw your spine.c change, and now it is working... thank you all

**Comment by netniV** [comment]
Sounds promising.  As for the new_hostname, not sure if that's something I introduced or someone else without getting some time to look at the code properly this weekend. IF we have a working patch, we will look to merge it as long as it also has the CHANGELOG info for the relevant issues it corrects.

**Comment by majed17** [comment]
i am a programming newbie or even baby, but some of the things i know for sure, is that: the guilty always justify themselves while the saints accept slander as the truth...

**Comment by eriksejr** [comment]
I'm going to close this pull request and create a new one for this and the other issues

**Comment by netniV** [comment]
> i am a programming newbie or even baby, but some of the things i know for sure, is that: the guilty always justify themselves while the saints accept slander as the truth...

I wouldn't have called you guilty.  @eriksejr appreciate your efforts on this one, I'll try and review over the weekend.

**Comment by majed17** [comment]
this is not the first time and why hop away?

**Comment by netniV** [comment]
I'm really not sure what you are getting at so I will use guesswork. 

If it is at my caution for applying the changes without properly reviewing the code, then that is because it had already been running for weeks prior to release without showing these symptoms.  Also, there are several suggestions for other fixes which combined should correct a few issues so a proper review is needed. 

Not sure why you would complain at that.  We obviously want to make sure that the fixes are correct which you have confirmed this working for you so that's a positive confirmation that will be taken into account, thanks.

Patience young padiwan, butif my guesswork is incorrect, well unless it's really going to fix something, maybe we should just leave it there.

**Comment by majed17** [comment]
a weird way to be using, so you have a crystal ball ?

**Comment by netniV** [comment]
Several, but with hind sight, everything can become crystal clear.

**Pull request closed without merging**
